=== eaoliveira/DSJ-N1602/Eduardo-Eduardo1-1/src/Xml/Exercicio/my/empresa.dtd
<!ELEMENT Empresa (funcionario+)>
<!ELEMENT funcionario (nome,telefone,departamento,empresa)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT telefone (#PCDATA)>
<!ATTLIST telefone ddd NMTOKEN #REQUIRED >
<!ATTLIST telefone ramal NMTOKEN #IMPLIED >
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>

=== eaoliveira/DSJ-N1602/Eduardo-Eduardo1-1/src/Xml/Exercicio/my/empresa.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="empresa.xsl"?>
<!--<!DOCTYPE xxx SYSTEM "empresa.dtd" > -->
<Empresa>

	<funcionario>
		<nome>Ze do bixiga</nome>
		<telefone ddd="11" ramal="1232">123456789</telefone>
		<departamento>Desenvolvimento</departamento>
		<empresa>NomeEmpresa</empresa>
	</funcionario>
	
	<funcionario>
		<nome>Paraiba da empilhadeira</nome>
		<telefone ddd="19" ramal="4444">987654321</telefone>
		<departamento>Fabrica</departamento>
		<empresa>NomeEmpresa1</empresa>
	</funcionario>
	
	<funcionario>
		<nome>Juca</nome>
		<telefone ddd="15" >12341234</telefone>
		<departamento>RH</departamento>
		<empresa>NomeEmpresa2</empresa>
	</funcionario>
	
</Empresa>
