=== eaoliveira/DSJ-N1602/JavaDev/src/Xml/filmes/filmes.dtd
<!ELEMENT filmes (filme+) >
<!ELEMENT filme (titulo, idade) >
<!ATTLIST filme estilo ( terror | infantil | comédia | ação | drama | suspense ) #REQUIRED >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT idade (#PCDATA) >

=== eaoliveira/DSJ-N1602/JavaDev/src/Xml/filmes/filmes.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="filmes.xsl"?>
<!DOCTYPE filmes SYSTEM "filmes.dtd" >
<filmes>
	<filme estilo="drama">
		<titulo>A Alegria</titulo>
		<idade>14 anos</idade>
	</filme>
	<filme estilo="suspense">
		<titulo>A Casa dos Sonhos</titulo>
		<idade>14 anos</idade>
	</filme>
	<filme estilo="drama">
		<titulo>A Chave de Sarah</titulo>
		<idade>10 anos</idade>
	</filme>
	<filme estilo="comédia">
		<titulo>Amizade Colorida</titulo>
		<idade>14 anos</idade>
	</filme>
	<filme estilo="ação">
		<titulo>Assalto ao Banco Central</titulo>
		<idade>14 anos</idade>
	</filme>
</filmes>
