=== eaoliveira/DSJ-N1602/Cleber/src/Xml/cadastroteste.dtd
<!ELEMENT cadastroteste (contato+)>
<!ELEMENT contato (nome, telefone, departamento, empresa)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT telefone (#PCDATA)>
<!ATTLIST telefone ddd NMTOKEN #REQUIRED>
<!ATTLIST telefone ramal NMTOKEN #IMPLIED>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>

=== eaoliveira/DSJ-N1602/Cleber/src/Xml/cadastroteste.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cadastroteste SYSTEM "cadastroteste.dtd" >
<cadastroteste>
		<contato>
		<nome>nome</nome>
		<telefone ddd="nmtoken">telefone</telefone>
		<departamento>departamento</departamento>
		<empresa>empresa</empresa>
	</contato>
		<contato>
			<nome>nome</nome>
			<telefone ddd="nmtoken" ramal="11">telefone</telefone>
			<departamento>departamento</departamento>
			<empresa>empresa</empresa>
		</contato>
		<contato>
			<nome>nome</nome>
			<telefone ddd="nmtoken" ramal="12">telefone</telefone>
			<departamento>departamento</departamento>
			<empresa>empresa</empresa>
		</contato>
</cadastroteste>
