=== eaoliveira/DSJ-N1602/LucasSantos01/src/XML/produto.dtd
<!ELEMENT collection (produto*)>
<!ELEMENT produto (id,nome,descricao,preco)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT descricao (#PCDATA)>
<!ELEMENT preco (#PCDATA)>

=== eaoliveira/DSJ-N1602/Eduardo-aulaRESTFull/src/br/com/edu/xml/NewFile.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE collection SYSTEM "produto.dtd">
<collection>
	<produto>
		<id>0</id>
		<nome>Not</nome>
		<descricao>Uma puta maquina com Ubuntu</descricao>
		<preco>1000</preco>
	</produto>
	<produto>
		<id>0</id>
		<nome>Not2</nome>
		<descricao>Uma puta maquina com Win</descricao>
		<preco>4000</preco>
	</produto>
</collection>
