=== eaoliveira/DSJ-N1602/JavaDev/src/Xml/resposta/contato/contatos.dtd
<!ELEMENT contatos (contato*)>
<!ELEMENT contato (nome, telefone+, departamento, empresa)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT telefone EMPTY>
<!ATTLIST telefone ddd NMTOKEN #IMPLIED>
<!ATTLIST telefone numero NMTOKEN #REQUIRED>
<!ATTLIST telefone ramal NMTOKEN #IMPLIED>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>

=== eaoliveira/DSJ-N1602/JavaDev/src/Xml/contatos.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="application/xml" href="contatos.xsl"?>
<!DOCTYPE contatos SYSTEM "contatos.dtd">
<contatos>
	<contato>
		<nome>Fulano da Silva</nome>
		<telefone ddd="11" numero="1234-1231" ramal="23" />
		<departamento>Gerenciamento de Redes</departamento>
		<empresa>Metrô</empresa>
	</contato>
	<contato>
		<nome>Beltrano de Azevedo</nome>
		<telefone numero="4564-1345" />
		<telefone numero="8549-5234" />
		<departamento>Tecnologia da Informação</departamento>
		<empresa>Itaú Telecom</empresa>
	</contato>
	<contato>
		<nome>Ciclano de Souza</nome>
		<telefone numero="8978-1345" />
		<departamento>Contador</departamento>
		<empresa>Bradesco</empresa>
	</contato>
	<contato>
		<nome>Xiquinha da Silva</nome>
		<telefone numero="98435-1345" />
		<departamento>Vendedora</departamento>
		<empresa>Autonoma</empresa>
	</contato>
</contatos>
